### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by 3togo** [iapatil/depth-semantic-fully-conv#6]
Pls help

Below is the dump after running "python main.py"

Joe

Loading images...
Loading data...
/usr/local/lib/python2.7/dist-packages/torch/nn/modules/loss.py:206: UserWarning: NLLLoss2d has been deprecated. Please use NLLLoss instead as a drop-in replacement and see http://pytorch.org/docs/master/nn.html#torch.nn.NLLLoss for more details.
  warnings.warn("NLLLoss2d has been deprecated. "
=> no checkpoint found at 'model_best.pth.tar'
Starting epoch 1 / 50
Learning Rate for this epoch: 1e-05
/usr/local/lib/python2.7/dist-packages/torch/nn/modules/upsampling.py:225: UserWarning: nn.UpsamplingBilinear2d is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.UpsamplingBilinear2d is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python2.7/dist-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/home/jc/git/depth-semantic-fully-conv/utils.py:69: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  loss = loss_fn(m(pred_labels), y_var)
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    loss = run_epoch(model, loss_fn, train_loader, optimizer, dtype)
  File "/home/jc/git/depth-semantic-fully-conv/utils.py", line 74, in run_epoch
    loss.backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: out of memory

**Comment by sjwhhhi** [comment]
Have you sloved the problem？ I met the same problem. Thx!

**Comment by 3togo** [comment]
Negative

**Comment by iapatil** [comment]
Please change batch size to 8 in main.py and let me know if this is fixed. Thanks!
